### PR TITLE
Authorizations

### PR DESCRIPTION
**Pull request by 2bleO**
**In this PR**

1. Install CanCanCan

2. Add a role column to the users table

3. User can delete a post if it is theirs or if they have an admin role (column role has value "admin"):
- Add the "Delete" button to the view

4. User can delete a comment if it is theirs or if they have an admin role (column role has value "admin"):
- Add the "Delete" button to the view

### CODE REVIEW

**Review by o-rashad — CHANGES_REQUESTED** [review]
Asslam Alikom @2bleO  

Hi 👋🏽, While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

You have submitted a pull request, that doesn't correspond to project to be submitted.

Your pull request is for `authorization` project and you submitted a code reviw for `documentation` project.


Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Happy coding!👏:heart:

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

> **_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

> _Invalid Code Review Request **Does not count** into the code reviews limit._

**Comment by 2bleO** [comment]
@od-c0d3r I have no “documentation” project this week. And as you can see in the image below, I did submit the correct project
Untitled
.

**Review by rloterh — APPROVED** [review]
## Status: Approved :heavy_check_mark:

Hi Onesis,  

Your project is complete! Great job for nailing it right on the first attempt 🥇. There is nothing else to say other than... it's time to merge it 🍾🚢 :shipit: . Congratulations!  🎉💯🌟 

## Good Points 👍
- Descriptive Pull Request
- Authorization well implemented
- Good ReadMe
- No linter errors

Cheers..Happy coding!..and keep soaring higher! 💻 🍷 🚀 

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have 2 more limited reviews per this project. If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by o-rashad** [comment]
> @od-c0d3r I have no “documentation” project this week. And as you can see in the image below, I did submit the correct project Untitled .

Thanks for your feedback @2bleO ,
this is probably caused by a bug
i will forward the issue to the dev team.

Sorry for the inconvenience

**Pull request merged**
